import React from "react";
import { useUser } from "../contexts/UserContext";
import GoalSummaryCard from "../components/GoalSummaryCard";
import AIJobRoadmap from "../components/AIJobRoadmap";

export default function RoadmapPage() {
  const { userGoals = null } = useUser();

  return (
    <section className="max-w-6xl mx-auto px-6 py-12 text-gray-800 dark:text-gray-200">
      <div className="flex items-start justify-between mb-6">
        <div>
          <h1 className="text-3xl font-bold text-indigo-600">Your AI-Powered Roadmap</h1>
          <p className="text-gray-600 mt-1">A tailored month-by-month study plan generated by Cybercode AI Advisor.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-white dark:bg-gray-900 p-6 rounded-2xl shadow border">
            <AIJobRoadmap goals={userGoals} />
          </div>
        </div>

        <aside className="space-y-6">
          <GoalSummaryCard goals={userGoals} />
          <div className="bg-white dark:bg-gray-900 p-4 rounded-2xl shadow border">
            <h4 className="text-sm font-semibold text-indigo-600">Tips</h4>
            <ul className="mt-3 text-sm text-gray-600">
              <li>Follow the roadmap in 2–4 week sprints for best retention.</li>
              <li>Ship one small project every 6–8 weeks.</li>
              <li>Use the AI mentor to prepare interview answers.</li>
            </ul>
          </div>
        </aside>
      </div>
    </section>
  );
}
