import React from "react";
import { motion } from "framer-motion";
import { useUser } from "../contexts/UserContext";
import GoalSummaryCard from "../components/GoalSummaryCard";
import GoalRoadmap from "../components/GoalRoadmap";
import AIJobRoadmap from "../components/AIJobRoadmap";

export default function RoadmapPage() {
  const { userGoals = null } = useUser();

  return (
    <section className="max-w-6xl mx-auto px-6 py-12 text-gray-800 dark:text-gray-200">
      <motion.div
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex items-start justify-between mb-8"
      >
        <div>
          <h1 className="text-3xl font-bold text-indigo-600">
            Your AI-Powered Roadmap
          </h1>
          <p className="text-gray-600 dark:text-gray-400 mt-1">
            A personalized, month-by-month study plan generated by Cybercode AI.
          </p>
        </div>
      </motion.div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* MAIN CONTENT */}
        <div className="lg:col-span-2 space-y-8">
          <motion.div
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            className="bg-white dark:bg-gray-900 p-6 rounded-2xl shadow border"
          >
            <GoalRoadmap goals={userGoals} />
          </motion.div>

          {/* Temporarily hide AI roadmap */}
          {/* Remove this when enabling AI roadmap */}
          {false && (
            <motion.div
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-white dark:bg-gray-900 p-6 rounded-2xl shadow border"
            >
              <AIJobRoadmap goals={userGoals} />
            </motion.div>
          )}

          {/* SIDEBAR */}
          <aside className="space-y-6">
            <GoalSummaryCard goals={userGoals} />

            <div className="bg-white dark:bg-gray-900 p-4 rounded-2xl shadow border">
              <h4 className="text-sm font-semibold text-indigo-600">Tips</h4>
              <ul className="mt-3 text-sm text-gray-600 dark:text-gray-300 space-y-2">
                <li>Follow the roadmap in 2–4 week sprints for best retention.</li>
                <li>Ship one measurable project every 6–8 weeks.</li>
                <li>Use the AI mentor to prepare interview answers.</li>
              </ul>
            </div>
          </aside>
        </div>
    </section>
  );
}
